### ISSUE TITLE
To-Do + Issues

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/ShulkerArchives#1]
- [x] ~~`Weasley's Wildfire Whizbangs | Deluxe Edition` NBT Data doesn't work in-game (I need to use `.nbt copy` instead of `FS+I`)~~ **Fixed**
- [x] Background of site is horrible
- [x] ~~Table needs padding on sides, it's ultra-wide on steroids rn~~ Fixed
- [x] ~~README is already outdated/obsolete somehow~~ Touched up, it wasn't actually as bad as my 1am brain thought it was

**Comment by KadTheHunter** [comment]
All tasks done, site now in Beta? Release? v1.Gobbledeegook? It's done! That's all that matters :)
