### ISSUE TITLE
TO-DO LIST 2 ELECTRIC BOOGALOO: REVAMPED, REDONE, REWRITTEN, AND REPROCRASTINATED

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/ShulkerArchives#105]
- [x] ~~Rewrite text on Table Pages~~ Touched up, it didn't really need much
- [x] ~~Completely overhaul Navigation, 7 buttons is getting ridiculous~~ Didn't need overhaul, just some retouching to the styling/arrangement.
- [x] Add Guide pages, linked in one or both of Resources & separate Guides page. Start with ripping Map Data (see #guides channel, viewable by Archivists). // **Working on this currently**
- [x] ~~Add HD Heads (Resources + Guides) + some form of generator and tools for it (AjaxGb aka Soltoders [mc-uuid-converter](https://github.com/AjaxGb/mc-uuid-converter/blob/master/convert.js) at minimum)~~ Delayed indefinitely, until FZMM adds or doesn't add HD Head Support.

**Comment by KadTheHunter** [comment]
Finished in a7cc921a3baed5a8d89a9556bcddefc6781555de
