### ISSUE TITLE
SHULKER ARCHIVES TO-DO LIST 3: REVENGE OF THE LIST

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/ShulkerArchives#109]
This will ideally serve as the ultimate (and final) 'to-do' list for the Shulker Archives.

Items marked with '**PUBLIC**' are able to be done by anyone, items marked with '**KAD ONLY**' can only be done by me.

- [ ] Add descriptions to Kits, from roughly [Line 522](https://github.com/KadTheHunter/ShulkerArchives/blob/master/nbt/kits/Kits.json#L522) up to [Line 4236](https://github.com/KadTheHunter/ShulkerArchives/blob/master/nbt/kits/Kits.json#L4136), plus a handful of stragglers outside that scope. | **PUBLIC**
- [ ] Tag all Kits, ~~Unnamed Kits and Items~~, using the [Tagging Guidelines](https://github.com/KadTheHunter/ShulkerArchives/blob/master/CONTRIBUTING.md#tags) | **PUBLIC**
- [ ] Review the dSd5 and sithvsjedi plots | **KAD ONLY**
- [x] ~~Add [webNBT](https://github.com/iRath96/webNBT) by iRath96 to Resources | **PUBLIC**~~ ee384cd
- [x] ~~Include EnderEyeGame's [NBT Minifier](https://autocompressor.net/tools/nbt-minifier) tool in Resources | **PUBLIC**~~ 1ff29eff5249f3fba54ddb3f499be2e6c9be062f
- [x] ~~Include [ArmorStatues](https://modrinth.com/mod/armor-statues) and [NBT Void](https://modrinth.com/mod/nbt-void) in Resources | **PUBLIC**~~ 8f6fe2efd96bd60d1aa15f32444254d7e0774c08
- [x] ~~Include [map-to-img](https://github.com/mircokroon/minecraft-maps-to-images) in Resources | **PUBLIC**~~ 8f6fe2efd96bd60d1aa15f32444254d7e0774c08
- [ ] Retouch FAQ, Guides and Resources | **KAD ONLY**
- [x] ~~Fix the Spawn Eggs + 0.1 download | **PUBLIC**~~ fe190d0b69843bb2d8a9c2b73a9e3064e38474f2
- [x] ~~Review player inventory text files, possibly add to site somewhere, Misc. Page? | **KAD ONLY**~~ a9a58d4252af27de4b240342a8079352cd9e4431
- [ ] Continue work on Archives map | **KAD/ICE/ABDUL/MARIO ONLY**
- [x] ~~Link footer to GitHub | **PUBLIC**~~ 32fdc3bbfd5942fa346abfcb305f54b307297c9d d61431ae4caa5d4641cc387245dde397a87903a5
- [x] ~~Tag set items as part of set | **PUBLIC**~~ 6e9267260799c2dad67413bf534406819a9a840d
- [x] ~~Add notice about 1.20+- Signs, 1.20.2+- Potions | **PUBLIC**~~ 27ac403099acc8f97e196fab8707d7c5a5977e1a
- [x] ~~Mark karma kits as scider per author request | **PUBLIC**~~ 6980aafe4d43ca454435b468d5f7fca1f25e23e5
- [x] ~~Tag MKW kits and alter description of MKW ripoff per MKW request | **PUBLIC**~~ 4955aad4ec9f81f26af9e43143004a4b0161febe
- [x] ~~Add ObjToSchematic to Resources | **PUBLIC**~~ 3b52e4b53653b2641ec95c755027b5a0f3967c21
- [x] ~~Add CustomSkinLoader/HD Heads to Resources/Guides | **KAD ONLY**~~ 4993f031151c36726fe48512de950f83ce16bc9d
- [x] ~~Fix Arikkus Builder Set III download link, check others | **PUBLIC**~~ 590abf1d2f33ced44e83952585b1407caa1ab376
- [ ] Sort & Export the Book Collection sent in by MarioKartWii

**Comment by KadTheHunter** [comment]
Repository no longer maintained, site abandoned.
