### ISSUE TITLE
[To-Do] Long(er) Term List

### ISSUE THREAD

**Issue by KadTheHunter** [KadTheHunter/ShulkerArchives#4]
- [x] Add a "Single Items" page
- [x] Make passcodes b64 encoded or similar in source
- [x] Add [NBT Iceberg](https://icebergcharts.com/i/Mc_NBT_and_Exploits) to the site somewhere
- [x] ~~Make sorting tables ignore non a-z + 0-9 chars, so things like [, ], ╬, etc. can be used in names without messing up the sorting system~~ **Opted not to do this, as it's easier to just strip names of those characters. If we really want to include them, they can go in the description.**
- [x] Minify JavaScript
- [x] Change Link Color/Format on NBT pages
- [x] Remove Phantom relics (useless div/body tags and CSS)

**Comment by KadTheHunter** [comment]
- [ ] Recanvas Misc. Hallway, check for un-added kits, double check Authors on added kits

**Comment by KadTheHunter** [comment]
- [ ] Add an Akefu Raider style message somewhere that says something along the lines of "HOLY FUCKING SHIT I NEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEED TO USE COMMON OVERUSED WORDS IN MY KIT NAME OR I WILL FUCKING DIE AND IF I DON'T GET TO USE THESE STUPID FUCKING OVERUSED WORDS I WILL EXPLODE INTO A MILLION BILLION PIXELS HOLY FUCKING GINORMOUS BALLS OF PIXELSHIT"

**Comment by KadTheHunter** [comment]
- [ ] Remove the double Information button on Resources page

**Comment by KadTheHunter** [comment]
...and then immediately add something new:

- [ ] Rework the Buttons system, as 4 buttons on any page is too many, and the table pages have 7

**Comment by KadTheHunter** [comment]
> * Add [NBT Iceberg](https://icebergcharts.com/i/Mc_NBT_and_Exploits) to the site somewhere

This has been on here since February 13th, and I just now did it, Hooray, I guess?

**Comment by KadTheHunter** [comment]
- [ ] Add credit for SNBT Linter from [AjaxGb](https://github.com/AjaxGb/NBTLint)

**Comment by KadTheHunter** [comment]
Closed with the creation of #105.
